### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by OscarOrSomething** [MCBaumcraft24/EssentialsGreen-Sponge#2]
From `@phroa` on the sponge forums:

 > The license in your README file fundamentally conflicts with Git & GitHub. GitHub's TOS makes it clear that when you upload code to a public repo, you grant others express rights to view and fork (copy) the code.

 > Perhaps http://choosealicense.org can help you decide on another one, should you choose to change it.

**Comment by OscarOrSomething** [comment]
I recommend MIT

**Comment by Marco606598** [comment]
God :D

**Comment by Marco606598** [comment]
?
